#ifndef PLAYBACK_INFO_ACTIONS_
#define PLAYBACK_INFO_ACTIONS_

enum PLAYBACK_INFO {
    PLAYBACK_TITLE,
    PLAYBACK_AUTHORS,

    PLAYBACK_NUMBER_OF_INFOS
};

enum PlaybackActions {
    PLAYBACK_PLAY_STOP,
    PLAYBACK_NEXT,
    PLAYBACK_PREVIOUS,

    PLAYBACK_NUMBER_OF_ACTIONS
};

#endif /* PLAYBACK_INFO_ACTIONS_ */
